config/urls.py
from django.conf import settings
from django.conf.urls import include as url_include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views

from contact_tracing.pages.views import about_page, home_page

admin.site.site_header = "Contact Tracing"
urlpatterns = [
    path("", view=home_page, name="home"),
    path("about/", view=about_page, name="about"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("contact_tracing.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("qr_code/", url_include("qr_code.urls", namespace="qr_code")),
    path(
        "companies/", include("contact_tracing.companies.urls", namespace="companies")
    ),
    path("pages/", include("contact_tracing.pages.urls", namespace="pages")),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

contact_tracing/companies/urls.py
from django.urls import path

from contact_tracing.companies.views import company_detail_view, contact_create_view

app_name = "companies"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<int:pk>/~create/", view=contact_create_view, name="contacts-create"),
    path("<int:pk>/", view=company_detail_view, name="detail"),
]

contact_tracing/pages/urls.py
from django.urls import path

from contact_tracing.pages.views import page_detail_view

app_name = "users"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    path("<str:slug>/", view=page_detail_view, name="detail"),
]

contact_tracing/users/urls.py
from django.urls import path

from contact_tracing.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

contact_tracing/companies/models.py
import datetime

import pusher
from colorfield.fields import ColorField
from django.conf import settings
from django.contrib.auth.models import Group, Permission
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from guardian.shortcuts import assign_perm


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200, default="", blank=True)
    image = models.URLField(blank=True)
    brand_color = ColorField(default="#c4dce8")
    button_color = ColorField(default="#007bff")
    background_color = ColorField(default="#007bff")
    button_text_color = ColorField(default="#fff")
    outline_button = models.BooleanField(default=False)
    phone_number_required = models.BooleanField(default=True)
    email_required = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Companies"
        permissions = [
            ("view_company_contacts", "Can view company contacts"),
            # ("close_task", "Can remove a task by setting its status as closed"),
        ]

    def __str__(self) -> str:
        return self.name


class ContactManager(models.Manager):
    def create_contact(self, company, name, phone_number, email):
        contact = Contact(
            name=name, phone_number=phone_number, company=company, email=email
        )
        contact.save()
        print(contact)
        # do something with the contact
        return contact


class Contact(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    company = ForeignKey(Company, on_delete=models.DO_NOTHING)
    phone_number = models.CharField(max_length=20, default="")
    email = models.EmailField(default="")
    objects = ContactManager()

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-created_at"]

    def was_added_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(weeks=3) <= self.created_at <= now

    was_added_recently.admin_order_field = "created_at"
    was_added_recently.boolean = True
    was_added_recently.short_description = "Within three weeks?"


pusher_client = pusher.Pusher(
    app_id=settings.PUSHER_APP_ID,
    key="dd24f028ebf4c08149d2",
    secret=settings.PUSHER_SECRET,
    cluster="us3",
    ssl=True,
)


def get_permission(req):
    perm = Permission.objects.get(codename=req)
    return perm


@receiver(post_save, sender=Company)
def company_post_save_receiver(sender, **kwargs):
    company = kwargs["instance"]
    # if created:
    group, crea = Group.objects.get_or_create(name=f"company_{company.id}")
    print(crea)
    # group = Group.objects.create(name=f"company_{company.id}")
    # Employee Permissions
    assign_perm(get_permission("view_company_contacts"), group, company)
    assign_perm(get_permission("change_company"), group, company)
    assign_perm(get_permission("view_company"), group, company)
    # Manager Permissions
    # assign_perm(get_permission('change_company'), manager_group, company)
    # assign_perm(get_permission('change_user'), manager_group, company)


@receiver(post_save, sender=Contact)
def contact_post_save_receiver(sender, **kwargs):
    contact, created = kwargs["instance"], kwargs["created"]
    print(contact, created, sender, kwargs)
    pusher_client.trigger(
        "contact-added",
        str(contact.company.id),
        {
            "name": contact.name,
            "email": contact.email,
            "phone_number": contact.phone_number,
            "id": contact.id,
        },
    )

contact_tracing/pages/models.py
from django.db import models
from tinymce import models as tinymce_models


# Create your models here.
class Page(models.Model):
    name = models.CharField(max_length=200)
    data = tinymce_models.HTMLField()
    slug = models.SlugField()
    jumbo = models.BooleanField(default=True)
    bg_image = models.URLField(
        verbose_name="Background Image",
        default="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=80",  # noqa: E501
    )

    def __str__(self):
        return self.name

contact_tracing/companies/forms.py
from crispy_forms.helper import FormHelper
from django import forms


class AddContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "id-exampleForm"

    name = forms.CharField(label="Name", required=True)
    phone_number = forms.CharField(label="Phone Number", required=False)
    company_id = forms.IntegerField(widget=forms.HiddenInput())
    email = forms.EmailField(required=False)


# class CompanyForm(forms.ModelForm):
#     # def __init__(self, *args, **kwargs):
#     #     super().__init__(*args, **kwargs)
#     #     self.helper = FormHelper()
#     #     self.helper.form_id = "id-exampleForm"

#     # name = forms.CharField(label="Name", required=True)
#     # phone_number = forms.CharField(
#     #     label="Phone Number",
#     #     # required=False
#     # )
#     # company_id = forms.IntegerField(widget=forms.HiddenInput())
#     model = Company
#     brand_color = forms.CharField(
#         label="Brand Color",
#         # initial="#e66465",
#         widget=TextInput({
#             "type": "color",
#             "value": "#e66465"
#         })

#     )

contact_tracing/pages/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from tinymce.widgets import TinyMCE

from .models import Page


class PageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "id-exampleForm"

    name = forms.CharField(label="Name", required=True)
    content = forms.CharField(widget=TinyMCE(attrs={"cols": 80, "rows": 30}))

    class Meta:
        model = Page

contact_tracing/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

contact_tracing/companies/views.py
from colormap import hls2rgb, rgb2hex, rgb2hls
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from guardian.mixins import PermissionRequiredMixin

from contact_tracing.companies.forms import AddContactForm

from .models import Company, Contact


class CompanyDetailView(PermissionRequiredMixin, DetailView):
    model = Company

    template_name = "companies/detail.html"
    permission_required = "companies.view_company_contacts"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        path = self.request.get_full_path() + "~create/"
        path = self.request.build_absolute_uri(path)
        print(path)
        context["create_link"] = path
        context["contacts"] = context["company"].contact_set.all()[:20]
        return context


company_detail_view = CompanyDetailView.as_view()


def get_companypk(path):
    numbers = []
    for word in path.split("/"):
        if word.isdigit():
            numbers.append(int(word))
    if len(numbers) > 0:
        # print(numbers)
        return numbers[0]
    return 0


def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip("#")
    hlen = len(hex_color)
    return tuple(
        int(hex_color[i : i + hlen // 3], 16)  # noqa: E203
        for i in range(0, hlen, hlen // 3)  # noqa: E203
    )


def adjust_color_lightness(r, g, b, factor):
    h, ls, s = rgb2hls(r / 255.0, g / 255.0, b / 255.0)
    ls = max(min(ls * factor, 1.0), 0.0)
    r, g, b = hls2rgb(h, ls, s)
    return rgb2hex(int(r * 255), int(g * 255), int(b * 255))


def darken_color(r, g, b, factor=0.1):
    return adjust_color_lightness(r, g, b, 1 - factor)


def darken_hex(hex_color, factor=1.15):
    r, g, b = hex_to_rgb(hex_color)
    return adjust_color_lightness(r, g, b, factor)


class ContactCreateView(FormView):
    model = Contact
    form_class = AddContactForm
    template_name = "companies/create_checkin.html"
    # def get_object(self):
    #     return User.objects.get(username=self.request.user.username)
    # fields = ["name", "phone_number"]
    # success_url =

    # def __init__(self) -> None:
    #     numbers = []
    #     for word in self.request.path.split("/"):
    #         if word.isdigit():
    #             numbers.append(int(word))
    #     if len(numbers) > 0:
    #         # print(numbers)
    #         self.primary_key = numbers[0]
    #     self.primary_key = 0

    def get_context_data(self, **kwargs):
        print(self.request)
        pk = get_companypk(self.request.path)

        context = super().get_context_data(**kwargs)
        print("PK", pk)
        company = get_object_or_404(Company, pk=pk)
        button_text_color = company.button_text_color
        button_color = company.button_color
        dark_button_color = darken_hex(company.button_color)
        background_color = company.background_color
        dark_background_color = darken_hex(company.background_color)
        context["company"] = company
        context["button_text_color"] = button_text_color
        context["button_color"] = button_color
        context["dark_button_color"] = dark_button_color
        context["background_color"] = background_color
        context["dark_background_color"] = dark_background_color
        print(dark_button_color)
        print(button_color)
        return context

    def get_success_url(self) -> str:
        print(self.request.path)
        return self.request.path

    def form_valid(self, form):

        self.add_check_in(form.cleaned_data)
        return super().form_valid(form)

    def get_initial(self):
        initial = super(ContactCreateView, self).get_initial()
        pk = get_companypk(self.request.path)
        initial.update({"company_id": pk})
        return initial

    def add_check_in(self, valid_data):
        company_id = valid_data["company_id"]
        name = valid_data["name"]
        phone_number = valid_data["phone_number"]
        email = valid_data["email"]
        company = Company.objects.get(id=company_id)
        Contact.objects.create_contact(company, name, phone_number, email)
        messages.add_message(
            self.request, messages.SUCCESS, "Check in successfully updated!"
        )
        print(valid_data)


contact_create_view = ContactCreateView.as_view()

# def create_checkin(request, company_id):
#     company = get_object_or_404(Company, pk=company_id)

#     if request.method == 'POST':
#         form = AddContactForm(request.POST)

#         if form.is_valid():

contact_tracing/pages/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView

from .models import Page


# Create your views here.
class PageDetailView(DetailView):

    model = Page
    slug_field = "slug"
    slug_url_kwarg = "slug"

    template_name = "pages/detail.html"


page_detail_view = PageDetailView.as_view()


def home_page(request):
    page = get_object_or_404(Page, pk=1)
    context = {"page": page}
    return render(request, "pages/detail.html", context)


def about_page(request):
    page = get_object_or_404(Page, pk=2)
    context = {"page": page}
    return render(request, "pages/detail.html", context)

contact_tracing/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

contact_tracing/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}Contact Tracing{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Application to easily capture contact trace forms"
    />
    <meta name="author" content="Alex Wine" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

    {% block css %}

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% compress css %}
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet" />

    {% endcompress %} {% endblock %}

    <style>
      .navbar-light .navbar-toggler-icon {
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%280, 0, 0, 0.5%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
      }
    </style>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh">
    <main role="main" class="flex-shrink-0">
      {% block navigation %}
      <div class="mb-1">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
          <button
            class="navbar-toggler navbar-toggler-right"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Contact Tracing</a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
              {% comment %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              {% endcomment %} {% if request.user.company %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  class="nav-link"
                  href="{% url 'companies:detail' request.user.company.id  %}"
                  >{{ request.user.company }}</a
                >
              </li>
              {% endif %} {% if request.user.is_staff %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'admin:index'  %}">Admin</a>
              </li>
              {% endif %} {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  class="nav-link"
                  href="{% url 'users:detail' request.user.username  %}"
                  >{% trans "My Profile" %}</a
                >
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}"
                  >{% trans "Sign Out" %}</a
                >
              </li>
              {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  id="sign-up-link"
                  class="nav-link"
                  href="{% url 'account_signup' %}"
                  >{% trans "Sign Up" %}</a
                >
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  id="log-in-link"
                  class="nav-link"
                  href="{% url 'account_login' %}"
                  >{% trans "Sign In" %}</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </div>
      {% endblock %}
      <!-- heading -->
      {% block heading %} {% endblock heading%}
      <div class="container">
        {% if messages %} {% for message in messages %}
        <div
          class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
        >
          {{ message }}<button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %} {% endif %} {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
        {% endblock content %}
      </div>
    </main>

    {% block footer %}
    <footer class="footer mt-auto py-3 navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav justify-content-end">
          <li class="nav-item">
            <a
              href="mailto:incoming+alexwine-contact-trace-22009761-issue-@incoming.gitlab.com"
              class="nav-link"
              >Support</a
            >
          </li>
        </ul>
      </div>
    </footer>
    {% endblock footer %}

    <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
    <!-- place project specific Javascript in this file -->
    {% block addedjavascript %} {% endblock addedjavascript %}
  </body>
</html>